# Generated by Django 3.1.7 on 2021-02-24 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promise_keeper', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to=None)),
                ('score', models.IntegerField()),
                ('leader', models.CharField(max_length=50)),
                ('ruling', models.JSONField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=None)),
                ('score', models.IntegerField()),
                ('post', models.CharField(max_length=100)),
                ('since', models.DateField()),
                ('status', models.BooleanField()),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promise_keeper.party')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('category', models.CharField(max_length=15)),
                ('source', models.TextField()),
                ('status', models.CharField(choices=[('NC', 'Not Completed'), ('C', 'Completed'), ('P', 'Pending'), ('A', 'Abandoned')], default='NC', max_length=2)),
                ('p_source', models.TextField()),
                ('date', models.DateField()),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promise_keeper.politician')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promise_keeper.party')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promise_keeper.state')),
            ],
        ),
    ]
