# Generated by Django 3.1.7 on 2021-02-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promise_keeper', '0003_party_politician_promise_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name_plural': 'Parties'},
        ),
    ]
