# Generated by Django 3.1.7 on 2021-02-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise_keeper', '0004_auto_20210224_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='ruling',
        ),
        migrations.AddField(
            model_name='party',
            name='ruling',
            field=models.ManyToManyField(to='promise_keeper.State'),
        ),
    ]
