# Generated by Django 3.1.7 on 2021-02-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise_keeper', '0006_auto_20210224_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='slug',
            field=models.CharField(default='Null', max_length=130),
        ),
    ]
