# Generated by Django 3.1.7 on 2021-02-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise_keeper', '0007_promise_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='slug',
            field=models.CharField(default='', max_length=130),
        ),
        migrations.AddField(
            model_name='politician',
            name='slug',
            field=models.CharField(default='', max_length=130),
        ),
        migrations.AddField(
            model_name='promise',
            name='proof',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
