# Generated by Django 3.1.7 on 2021-02-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise_keeper', '0011_auto_20210225_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='logo',
            field=models.ImageField(upload_to='party'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='image',
            field=models.ImageField(upload_to='politician'),
        ),
    ]
