# Generated by Django 3.1.7 on 2021-03-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise_keeper', '0013_promise_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promise',
            name='category',
            field=models.CharField(max_length=30),
        ),
    ]
